config/routes.rb
Rails.application.routes.draw do
    devise_for :members, :controllers => { :registrations => "registrations" }

    resources :after_signup

    root "pages#show", page: "home"
    get "/pages/*page" => "pages#show"
end

app/models/member.rb
class Member < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise  :database_authenticatable, :registerable,
            :recoverable, :rememberable, :trackable, :validatable

    has_one :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :member, dependent: :destroy

    validates :firstname, presence: true
    validates :lastname, presence: true
end

app/controllers/after_signup_controller.rb
class AfterSignupController < ApplicationController
    include Wicked::Wizard

    before_filter :authenticate_member!
    steps :basic_info, :profile_type_choice

    def show
        @profile = current_profile
        render_wizard
    end

    def update
        @profile = current_profile
        case step
            when :basic_info
                @profile.update_attributes(profile_params)
            when :profile_type_choice
                # TODO - Create related profile based on this
                puts "Selected membership type: #{params[:membership][:membership_type]}"
        end

        render_wizard @profile
    end

    # def finish_wizard_path
    #     user_path(current_user)
    # end

    private

        def current_profile
            current_member.profile || current_member.create_profile
        end

        def profile_params
            params.require(:profile).permit(:firstname, :lastname, :location, :bio)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def resource_name
    :member
  end

  def resource
    @resource ||= Member.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:member]
  end

  helper_method :resource_name, :resource, :devise_mapping
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def show
        if valid_page?
            render template: "pages/#{params[:page]}"
        else
            render file: "public/404.html", status: :not_found
        end
    end

    private

    def valid_page?
        File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    def create
        super
    end

    protected

        def after_sign_up_path_for(resource)
            after_signup_path(:basic_info)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/after_signup/basic_info.html.erb
<h2>Thanks for signing up </h2>

<p>Add your basic info</p>

<%= form_for(@profile, :url => wizard_path, :method => :put) do |f| %>
    <%= f.text_field :firstname, :placeholder => 'First Name' %>
    <%= f.text_field :lastname, :placeholder => 'Last Name' %>
    <%= f.text_field :location, :placeholder => 'Location' %>
    <%= f.text_area :bio, :placeholder => 'Bio' %>
    <%= f.submit 'Next', :class => 'btn btn-primary' %>
<% end %>

<p>
    Some extra info: Member ID is <%= @profile.member_id %>
</p>

<%# link_to 'skip', next_wizard_path %>

app/views/after_signup/profile_type_choice.html.erb
<p>Choose your type</p>

<p>
    Hey there <%= @profile.firstname %>
</p>

<%= form_for("membership", :url => wizard_path, :method => :put) do |f| %>
    <%= f.select "membership_type", options_for_select([ "Dancer", "Host" ]) %>
    <%= f.submit 'Finish', :class => 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DanceCommunity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the Dance Community</h1>

<% if member_signed_in? %>
    <h2>Logged in user: <%= current_member.email %></h2>

    <%= link_to('Logout', destroy_member_session_path, :method => :delete) %>
<% else %>

    <div>
        <h2>Member? Log In!</h2>

        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <%= render "devise/sessions/form", f: f %>
        <% end %>
    </div>

    <div>
        <h2>New? <%= link_to "Sign up!", new_member_registration_path %></h2>
    </div>

<% end %>